export const TEXTS = {
  tabs: {
    employees: "Сотрудники",
    supervisoryCase: "Наблюдательное дело",
  },
  common: {
    defaultTitle: "Заголовок",
    defaultAction: "Действие",
    closeModal: "Закрыть модальное окно",
    expired: "ПРОСРОЧЕНО",
    cancel: "Отмена",
  },
  update: {
    available: "Доступна новая версия",
    action: "Нажмите, чтобы открыть страницу загрузки",
  },
  header: {
    update: "Обновить",
  },
  table: {
    noData: "Нет данных",
    totalRecords: "Всего записей",
  },
  app: {
    searchPlaceholder: "Поиск",
    onlyWithErrors: "Только с ошибками",
    generateDocuments: "Сгенерировать документы",
    generateDocument: "Сгенерировать документ",
    selectedCount: "Выбрано",
    people: "человек",
    chooseDocuments: "Выбор документов",
    settings: "Настройка",
    settingsTitle: "Настройки",
    hirePackage: "Принять на работу",
    firePackage: "Уволить",
    fileCreated: "Файл создан и находится на рабочем столе",
    fileError: "Ошибка при создании файла: ",
    packageCreated: "создано на рабочем столе",
    nonCompany: "Нет организации",
  },
  settings: {
    outgoingNumber: "Исходящий номер",
    hiringOrderNumber: "Приказ о приёме №",
    firingOrderNumber: "Приказ об увольнении №",
  },
  organisation: {
    add: "Добавить организацию",
    title: "Новая организация",
    uploadExcel: "Загрузить Excel с сотрудниками",
    fileChosen: "Файл выбран",
    save: "Сохранить",
    nameRequired: "Укажите название организации",
    created: "Организация добавлена",
    delete: "Удалить организацию",
    deleteConfirmStart: "Удалить организацию",
    deleteConfirmEnd: "и всех её сотрудников?",
    confirmDelete: "Удалить",
    deleted: "Организация удалена",
    fields: {
      name: "Название",
      ceo: "Директор (ФИО)",
      outgoingNumber: "Исходящий номер",
      hiringOrderNumber: "Приказ о приёме №",
      firingOrderNumber: "Приказ об увольнении №",
      licenseIssueDate: "Дата выдачи лицензии",
      licenseNumber: "Номер лицензии",
      legalAddress: "Юридический адрес",
      phone: "Телефон",
      email: "Email",
      numberOfDocument: "Номер документа",
    },
  },
  supervisory: {
    commonDocs: "Общие документы",
    objects: "Объекты",
    selectObject: "Выберите объект",
    noObjects: "Объектов пока нет",
    addObject: "Добавить объект",
    removeObject: "Удалить объект",
    objectTitle: "Новый объект",
    editObjectTitle: "Редактирование объекта",
    edit: "Редактировать",
    updated: "Объект обновлён",
    objectDocs: "Документы объекта",
    customer: "Заказчик",
    selectCustomerFirst: "Выберите заказчика",
    noCustomers: "Заказчиков пока нет",
    customerObjects: "Объекты заказчика",
    generate: "Сгенерировать",
    download: "Скачать",
    selectMonth: "Выберите месяц",
    monthRequired: "Сначала выберите месяц",
    months: [
      "Январь",
      "Февраль",
      "Март",
      "Апрель",
      "Май",
      "Июнь",
      "Июль",
      "Август",
      "Сентябрь",
      "Октябрь",
      "Ноябрь",
      "Декабрь",
    ],
    save: "Сохранить",
    addressRequired: "Укажите адрес объекта",
    fillAllFields: "Заполните все поля",
    customerRequired: "Сначала выберите заказчика",
    created: "Объект добавлен",
    removed: "Объект удалён",
    selectCustomer: "Выберите заказчика",
    uploadContract: "Загрузить договор",
    uploadInstruction: "Загрузить инструкцию",
    uploadScheme: "Загрузить схему",
    uploadOlrrNotice: "Загрузить уведомление ОЛРР",
    upload: "Загрузить",
    preview: "Предпросмотр",
    previewLoading: "Загрузка предпросмотра…",
    previewError: "Не удалось открыть предпросмотр: ",
    uploaded: "Файл загружен",
    savedToDevice: "Файл сохранён: ",
    saveError: "Не удалось сохранить файл: ",
    uploadError: "Ошибка загрузки файла: ",
    fileNotUploaded: "Файл не загружен",
    openError: "Не удалось открыть файл: ",
    fields: {
      address: "Адрес объекта",
      orgName: "Название организации (заказчик)",
      signatory: "Подписант",
      fullName: "ФИО",
      position: "Должность",
      contractNumber: "Номер договора",
      contractDate: "Дата договора",
    },
  },
  documents: {
    requestToCard: "Заявление на получение личной карточки",
    requestToEmployee: "Уведомление при приеме на работу",
    inventoryForRequestToCard: "Опись ЛК",
    requestToFire: "Уведомление об увольнении",
    requestFromOrganization: "Выписка из приказа об увольнении",
    generalLicense: "Генеральная лицензия",
    contract: "Договор",
    instruction: "Инструкция",
    scheme: "Схема",
    egrulExtract: "Выписка из ЕГРЮЛ",
    dutySchedule: "График несения службы",
    guardsOrder: "Приказ по охранникам",
    insuranceContract: "Договор страхования",
    formSample: "Образец формы",
    olrrNotice: "Уведомление ОЛРР",
  },
} as const;
